// src/levels.ts
import type { Level } from "./types";

export const LEVELS: Level[] = [
  {
    id: 1, title: "Bonjour", difficulty: "facile",
    statement: "Écris une fonction `bonjour()` qui **retourne** la chaîne `\"Bonjour\"`.",
    entry: "bonjour",
    starterCode: "def bonjour():\n    # retourne la chaîne \"Bonjour\"\n    pass\n",
    tests: [{ args: [], expected: "Bonjour" }],
    hiddenTests: [],
  },
  {
    id: 2, title: "Le double", difficulty: "facile",
    statement: "Retourne le double de `n`.",
    entry: "double",
    starterCode: "def double(n):\n    pass\n",
    tests: [{ args: [3], expected: 6 }, { args: [0], expected: 0 }],
    hiddenTests: [{ args: [-4], expected: -8 }],
  },
  {
    id: 3, title: "Somme", difficulty: "facile",
    statement: "Retourne la somme de `a` et `b`.",
    entry: "somme",
    starterCode: "def somme(a, b):\n    pass\n",
    tests: [{ args: [2, 3], expected: 5 }],
    hiddenTests: [{ args: [-1, 1], expected: 0 }, { args: [100, 250], expected: 350 }],
  },
  {
    id: 4, title: "Pair ou impair", difficulty: "facile",
    statement: "Retourne `True` si `n` est pair, sinon `False`.",
    entry: "est_pair",
    starterCode: "def est_pair(n):\n    pass\n",
    tests: [{ args: [4], expected: true }, { args: [7], expected: false }],
    hiddenTests: [{ args: [0], expected: true }, { args: [-3], expected: false }],
  },
  {
    id: 5, title: "Le plus grand", difficulty: "facile",
    statement: "Retourne le plus grand des deux nombres `a` et `b`.",
    entry: "maximum",
    starterCode: "def maximum(a, b):\n    pass\n",
    tests: [{ args: [3, 8], expected: 8 }, { args: [10, 2], expected: 10 }],
    hiddenTests: [{ args: [5, 5], expected: 5 }, { args: [-1, -9], expected: -1 }],
  },
  {
    id: 6, title: "Taille du mot", difficulty: "facile",
    statement: "Retourne le nombre de caractères de la chaîne `mot`.",
    entry: "taille",
    starterCode: "def taille(mot):\n    pass\n",
    tests: [{ args: ["chat"], expected: 4 }, { args: [""], expected: 0 }],
    hiddenTests: [{ args: ["bonjour"], expected: 7 }],
  },
  {
    id: 7, title: "Somme des pairs", difficulty: "moyen",
    statement: "Retourne la somme des nombres **pairs** de la liste `nombres`.",
    entry: "somme_pairs",
    starterCode: "def somme_pairs(nombres):\n    pass\n",
    tests: [{ args: [[1, 2, 3, 4]], expected: 6 }, { args: [[]], expected: 0 }],
    hiddenTests: [{ args: [[1, 3, 5]], expected: 0 }, { args: [[2, 4, 6, 8]], expected: 20 }],
  },
  {
    id: 8, title: "Compter les voyelles", difficulty: "moyen",
    statement: "Retourne le nombre de voyelles (a, e, i, o, u, y) dans `mot` (en minuscules).",
    entry: "compter_voyelles",
    starterCode: "def compter_voyelles(mot):\n    pass\n",
    tests: [{ args: ["bonjour"], expected: 3 }, { args: ["xyz"], expected: 1 }],
    hiddenTests: [{ args: [""], expected: 0 }, { args: ["aeiouy"], expected: 6 }],
  },
  {
    id: 9, title: "À l'envers", difficulty: "moyen",
    statement: "Retourne la chaîne `s` inversée.",
    entry: "inverser",
    starterCode: "def inverser(s):\n    pass\n",
    tests: [{ args: ["abc"], expected: "cba" }, { args: [""], expected: "" }],
    hiddenTests: [{ args: ["a"], expected: "a" }, { args: ["python"], expected: "nohtyp" }],
  },
  {
    id: 10, title: "FizzBuzz", difficulty: "moyen",
    statement: "Retourne une liste de 1 à `n`. Remplace les multiples de 3 par `\"Fizz\"`, de 5 par `\"Buzz\"`, de 15 par `\"FizzBuzz\"`.",
    entry: "fizzbuzz",
    starterCode: "def fizzbuzz(n):\n    pass\n",
    tests: [{ args: [5], expected: [1, 2, "Fizz", 4, "Buzz"] }],
    hiddenTests: [{ args: [15], expected: [1, 2, "Fizz", 4, "Buzz", "Fizz", 7, 8, "Fizz", "Buzz", 11, "Fizz", 13, 14, "FizzBuzz"] }],
  },
  {
    id: 11, title: "Palindrome", difficulty: "moyen",
    statement: "Retourne `True` si `s` se lit pareil à l'endroit et à l'envers.",
    entry: "est_palindrome",
    starterCode: "def est_palindrome(s):\n    pass\n",
    tests: [{ args: ["kayak"], expected: true }, { args: ["chien"], expected: false }],
    hiddenTests: [{ args: [""], expected: true }, { args: ["ressasser"], expected: true }],
  },
  {
    id: 12, title: "Factorielle", difficulty: "moyen",
    statement: "Retourne `n!` (factorielle de `n`). On a `0! = 1`.",
    entry: "factorielle",
    starterCode: "def factorielle(n):\n    pass\n",
    tests: [{ args: [5], expected: 120 }, { args: [0], expected: 1 }],
    hiddenTests: [{ args: [1], expected: 1 }, { args: [6], expected: 720 }],
  },
  {
    id: 13, title: "Maximum d'une liste", difficulty: "moyen",
    statement: "Retourne le plus grand élément de `nombres` **sans utiliser `max()`**. La liste n'est jamais vide.",
    entry: "maximum_liste",
    starterCode: "def maximum_liste(nombres):\n    pass\n",
    tests: [{ args: [[3, 7, 2, 9, 4]], expected: 9 }],
    hiddenTests: [{ args: [[-5, -1, -10]], expected: -1 }, { args: [[42]], expected: 42 }],
  },
  {
    id: 14, title: "Compter les occurrences", difficulty: "moyen",
    statement: "Retourne le nombre de fois où `x` apparaît dans la liste `liste`.",
    entry: "compter",
    starterCode: "def compter(liste, x):\n    pass\n",
    tests: [{ args: [[1, 2, 2, 3, 2], 2], expected: 3 }, { args: [[1, 2, 3], 9], expected: 0 }],
    hiddenTests: [{ args: [[], 1], expected: 0 }],
  },
  {
    id: 15, title: "Fibonacci", difficulty: "difficile",
    statement: "Retourne le `n`-ième terme de la suite de Fibonacci. `fib(0)=0`, `fib(1)=1`.",
    entry: "fibonacci",
    starterCode: "def fibonacci(n):\n    pass\n",
    tests: [{ args: [0], expected: 0 }, { args: [1], expected: 1 }, { args: [7], expected: 13 }],
    hiddenTests: [{ args: [10], expected: 55 }, { args: [20], expected: 6765 }],
  },
  {
    id: 16, title: "Nombre premier", difficulty: "difficile",
    statement: "Retourne `True` si `n` est un nombre premier, sinon `False`.",
    entry: "est_premier",
    starterCode: "def est_premier(n):\n    pass\n",
    tests: [{ args: [7], expected: true }, { args: [10], expected: false }, { args: [1], expected: false }],
    hiddenTests: [{ args: [2], expected: true }, { args: [97], expected: true }, { args: [0], expected: false }],
  },
  {
    id: 17, title: "Trier (sans sorted)", difficulty: "difficile",
    statement: "Retourne une **nouvelle** liste contenant les éléments de `nombres` triés par ordre croissant, **sans utiliser `sorted()` ni `.sort()`**.",
    entry: "trier",
    starterCode: "def trier(nombres):\n    pass\n",
    tests: [{ args: [[3, 1, 2]], expected: [1, 2, 3] }, { args: [[]], expected: [] }],
    hiddenTests: [{ args: [[5, 5, 1, 9, 1]], expected: [1, 1, 5, 5, 9] }, { args: [[-2, 0, -7]], expected: [-7, -2, 0] }],
  },
  {
    id: 18, title: "Deux nombres, une cible", difficulty: "difficile",
    statement: "Retourne la liste `[i, j]` des **indices** (i < j) de deux nombres de `nombres` dont la somme vaut `cible`. Retourne `None` s'il n'y en a pas. Il y a au plus une solution.",
    entry: "paire_somme",
    starterCode: "def paire_somme(nombres, cible):\n    pass\n",
    tests: [{ args: [[2, 7, 11, 15], 9], expected: [0, 1] }, { args: [[1, 2, 3], 100], expected: null }],
    hiddenTests: [{ args: [[3, 2, 4], 6], expected: [1, 2] }],
  },
  {
    id: 19, title: "Anagrammes", difficulty: "difficile",
    statement: "Retourne `True` si `a` et `b` sont des anagrammes (mêmes lettres, même nombre), sinon `False`.",
    entry: "sont_anagrammes",
    starterCode: "def sont_anagrammes(a, b):\n    pass\n",
    tests: [{ args: ["chien", "niche"], expected: true }, { args: ["abc", "abd"], expected: false }],
    hiddenTests: [{ args: ["", ""], expected: true }, { args: ["aab", "abb"], expected: false }],
  },
  {
    id: 20, title: "Somme maximale", difficulty: "difficile",
    statement: "Retourne la somme du sous-tableau **contigu** de somme maximale dans `nombres` (au moins un élément). Ex : `[-2,1,-3,4,-1,2,1,-5,4]` → `6` (`[4,-1,2,1]`).",
    entry: "max_sous_somme",
    starterCode: "def max_sous_somme(nombres):\n    pass\n",
    tests: [{ args: [[-2, 1, -3, 4, -1, 2, 1, -5, 4]], expected: 6 }],
    hiddenTests: [{ args: [[1]], expected: 1 }, { args: [[-3, -1, -2]], expected: -1 }, { args: [[5, 4, -1, 7, 8]], expected: 23 }],
  },
];

export const TOTAL_LEVELS = LEVELS.length;
