// src/levels.ts — généré, ne pas éditer à la main (cf. scripts/gen_levels.py)
import type { Level } from "./types";

export const THEMES = [
  { key: "premiers-pas", label: "Premiers pas" },
  { key: "conditions", label: "Conditions & logique" },
  { key: "boucles", label: "Boucles & accumulation" },
  { key: "chaines", label: "Chaînes de caractères" },
  { key: "algos", label: "Listes & algorithmique" },
] as const;

export const LEVELS: Level[] = [
  {
    id: 1, title: "Bonjour", difficulty: "facile", theme: "premiers-pas",
    statement: "Écris une fonction `bonjour()` qui **retourne** la chaîne `\"Bonjour\"`.",
    starterCode: "def bonjour():\n    pass\n",
    entry: "bonjour",
    tests: [{ args: [], expected: "Bonjour" }],
    hiddenTests: [],
  },
  {
    id: 2, title: "Le double", difficulty: "facile", theme: "premiers-pas",
    statement: "Retourne le double de `n`.",
    starterCode: "def double(n):\n    pass\n",
    entry: "double",
    tests: [{ args: [3], expected: 6 }, { args: [0], expected: 0 }],
    hiddenTests: [{ args: [-4], expected: -8 }],
  },
  {
    id: 3, title: "Somme", difficulty: "facile", theme: "premiers-pas",
    statement: "Retourne la somme de `a` et `b`.",
    starterCode: "def somme(a, b):\n    pass\n",
    entry: "somme",
    tests: [{ args: [2, 3], expected: 5 }],
    hiddenTests: [{ args: [-1, 1], expected: 0 }, { args: [100, 250], expected: 350 }],
  },
  {
    id: 4, title: "Pair ou impair", difficulty: "facile", theme: "conditions",
    statement: "Retourne `True` si `n` est pair, sinon `False`.",
    starterCode: "def est_pair(n):\n    pass\n",
    entry: "est_pair",
    tests: [{ args: [4], expected: true }, { args: [7], expected: false }],
    hiddenTests: [{ args: [0], expected: true }, { args: [-3], expected: false }],
  },
  {
    id: 5, title: "Le plus grand", difficulty: "facile", theme: "conditions",
    statement: "Retourne le plus grand des deux nombres `a` et `b`.",
    starterCode: "def maximum(a, b):\n    pass\n",
    entry: "maximum",
    tests: [{ args: [3, 8], expected: 8 }, { args: [10, 2], expected: 10 }],
    hiddenTests: [{ args: [5, 5], expected: 5 }, { args: [-1, -9], expected: -1 }],
  },
  {
    id: 6, title: "Taille du mot", difficulty: "facile", theme: "premiers-pas",
    statement: "Retourne le nombre de caractères de la chaîne `mot`.",
    starterCode: "def taille(mot):\n    pass\n",
    entry: "taille",
    tests: [{ args: ["chat"], expected: 4 }, { args: [""], expected: 0 }],
    hiddenTests: [{ args: ["bonjour"], expected: 7 }],
  },
  {
    id: 7, title: "Somme des pairs", difficulty: "moyen", theme: "boucles",
    statement: "Retourne la somme des nombres **pairs** de la liste `nombres`.",
    starterCode: "def somme_pairs(nombres):\n    pass\n",
    entry: "somme_pairs",
    tests: [{ args: [[1, 2, 3, 4]], expected: 6 }, { args: [[]], expected: 0 }],
    hiddenTests: [{ args: [[1, 3, 5]], expected: 0 }, { args: [[2, 4, 6, 8]], expected: 20 }],
  },
  {
    id: 8, title: "Compter les voyelles", difficulty: "moyen", theme: "chaines",
    statement: "Retourne le nombre de voyelles (`a e i o u y`) dans `mot` (en minuscules).",
    starterCode: "def compter_voyelles(mot):\n    pass\n",
    entry: "compter_voyelles",
    tests: [{ args: ["bonjour"], expected: 3 }, { args: ["xyz"], expected: 1 }],
    hiddenTests: [{ args: [""], expected: 0 }, { args: ["aeiouy"], expected: 6 }],
  },
  {
    id: 9, title: "À l'envers", difficulty: "moyen", theme: "chaines",
    statement: "Retourne la chaîne `s` inversée.",
    starterCode: "def inverser(s):\n    pass\n",
    entry: "inverser",
    tests: [{ args: ["abc"], expected: "cba" }, { args: [""], expected: "" }],
    hiddenTests: [{ args: ["a"], expected: "a" }, { args: ["python"], expected: "nohtyp" }],
  },
  {
    id: 10, title: "FizzBuzz", difficulty: "moyen", theme: "boucles",
    statement: "Retourne une liste de 1 à `n`. Remplace les multiples de 3 par `\"Fizz\"`, de 5 par `\"Buzz\"`, de 15 par `\"FizzBuzz\"`.",
    starterCode: "def fizzbuzz(n):\n    pass\n",
    entry: "fizzbuzz",
    tests: [{ args: [5], expected: [1, 2, "Fizz", 4, "Buzz"] }],
    hiddenTests: [{ args: [15], expected: [1, 2, "Fizz", 4, "Buzz", "Fizz", 7, 8, "Fizz", "Buzz", 11, "Fizz", 13, 14, "FizzBuzz"] }],
  },
  {
    id: 11, title: "Palindrome", difficulty: "moyen", theme: "chaines",
    statement: "Retourne `True` si `s` se lit pareil à l'endroit et à l'envers.",
    starterCode: "def est_palindrome(s):\n    pass\n",
    entry: "est_palindrome",
    tests: [{ args: ["kayak"], expected: true }, { args: ["chien"], expected: false }],
    hiddenTests: [{ args: [""], expected: true }, { args: ["ressasser"], expected: true }],
  },
  {
    id: 12, title: "Factorielle", difficulty: "moyen", theme: "boucles",
    statement: "Retourne `n!` (factorielle de `n`). On a `0! = 1`.",
    starterCode: "def factorielle(n):\n    pass\n",
    entry: "factorielle",
    tests: [{ args: [5], expected: 120 }, { args: [0], expected: 1 }],
    hiddenTests: [{ args: [1], expected: 1 }, { args: [6], expected: 720 }],
  },
  {
    id: 13, title: "Maximum d'une liste", difficulty: "moyen", theme: "algos",
    statement: "Retourne le plus grand élément de `nombres` **sans utiliser `max()`**. La liste n'est jamais vide.",
    starterCode: "def maximum_liste(nombres):\n    pass\n",
    entry: "maximum_liste",
    tests: [{ args: [[3, 7, 2, 9, 4]], expected: 9 }],
    hiddenTests: [{ args: [[-5, -1, -10]], expected: -1 }, { args: [[42]], expected: 42 }],
  },
  {
    id: 14, title: "Compter les occurrences", difficulty: "moyen", theme: "boucles",
    statement: "Retourne le nombre de fois où `x` apparaît dans `liste`.",
    starterCode: "def compter(liste, x):\n    pass\n",
    entry: "compter",
    tests: [{ args: [[1, 2, 2, 3, 2], 2], expected: 3 }, { args: [[1, 2, 3], 9], expected: 0 }],
    hiddenTests: [{ args: [[], 1], expected: 0 }],
  },
  {
    id: 15, title: "Fibonacci", difficulty: "difficile", theme: "algos",
    statement: "Retourne le `n`-ième terme de la suite de Fibonacci. `fib(0)=0`, `fib(1)=1`.",
    starterCode: "def fibonacci(n):\n    pass\n",
    entry: "fibonacci",
    tests: [{ args: [0], expected: 0 }, { args: [1], expected: 1 }, { args: [7], expected: 13 }],
    hiddenTests: [{ args: [10], expected: 55 }, { args: [20], expected: 6765 }],
  },
  {
    id: 16, title: "Nombre premier", difficulty: "difficile", theme: "algos",
    statement: "Retourne `True` si `n` est un nombre premier, sinon `False`.",
    starterCode: "def est_premier(n):\n    pass\n",
    entry: "est_premier",
    tests: [{ args: [7], expected: true }, { args: [10], expected: false }, { args: [1], expected: false }],
    hiddenTests: [{ args: [2], expected: true }, { args: [97], expected: true }, { args: [0], expected: false }],
  },
  {
    id: 17, title: "Trier (sans sorted)", difficulty: "difficile", theme: "algos",
    statement: "Retourne une **nouvelle** liste avec les éléments de `nombres` triés par ordre croissant, **sans `sorted()` ni `.sort()`**.",
    starterCode: "def trier(nombres):\n    pass\n",
    entry: "trier",
    tests: [{ args: [[3, 1, 2]], expected: [1, 2, 3] }, { args: [[]], expected: [] }],
    hiddenTests: [{ args: [[5, 5, 1, 9, 1]], expected: [1, 1, 5, 5, 9] }, { args: [[-2, 0, -7]], expected: [-7, -2, 0] }],
  },
  {
    id: 18, title: "Deux nombres, une cible", difficulty: "difficile", theme: "algos",
    statement: "Retourne la liste `[i, j]` des indices (i < j) de deux nombres de `nombres` dont la somme vaut `cible`, ou `None`. Au plus une solution.",
    starterCode: "def paire_somme(nombres, cible):\n    pass\n",
    entry: "paire_somme",
    tests: [{ args: [[2, 7, 11, 15], 9], expected: [0, 1] }, { args: [[1, 2, 3], 100], expected: null }],
    hiddenTests: [{ args: [[3, 2, 4], 6], expected: [1, 2] }],
  },
  {
    id: 19, title: "Anagrammes", difficulty: "difficile", theme: "chaines",
    statement: "Retourne `True` si `a` et `b` sont des anagrammes (mêmes lettres, même nombre).",
    starterCode: "def sont_anagrammes(a, b):\n    pass\n",
    entry: "sont_anagrammes",
    tests: [{ args: ["chien", "niche"], expected: true }, { args: ["abc", "abd"], expected: false }],
    hiddenTests: [{ args: ["", ""], expected: true }, { args: ["aab", "abb"], expected: false }],
  },
  {
    id: 20, title: "Somme maximale", difficulty: "difficile", theme: "algos",
    statement: "Retourne la somme du sous-tableau **contigu** de somme maximale (au moins un élément). Ex : `[-2,1,-3,4,-1,2,1,-5,4]` → `6`.",
    starterCode: "def max_sous_somme(nombres):\n    pass\n",
    entry: "max_sous_somme",
    tests: [{ args: [[-2, 1, -3, 4, -1, 2, 1, -5, 4]], expected: 6 }],
    hiddenTests: [{ args: [[1]], expected: 1 }, { args: [[-3, -1, -2]], expected: -1 }, { args: [[5, 4, -1, 7, 8]], expected: 23 }],
  },
  {
    id: 21, title: "Valeur absolue", difficulty: "facile", theme: "premiers-pas",
    statement: "Retourne la valeur absolue de `n` (sa version positive), **sans utiliser `abs()`**.",
    starterCode: "def valeur_absolue(n):\n    pass\n",
    entry: "valeur_absolue",
    tests: [{ args: [-5], expected: 5 }, { args: [3], expected: 3 }, { args: [0], expected: 0 }],
    hiddenTests: [{ args: [-100], expected: 100 }, { args: [42], expected: 42 }],
  },
  {
    id: 22, title: "Le carré", difficulty: "facile", theme: "premiers-pas",
    statement: "Retourne le carré de `n` (c'est-à-dire `n × n`).",
    starterCode: "def carre(n):\n    pass\n",
    entry: "carre",
    tests: [{ args: [3], expected: 9 }, { args: [0], expected: 0 }, { args: [-4], expected: 16 }],
    hiddenTests: [{ args: [12], expected: 144 }, { args: [10], expected: 100 }],
  },
  {
    id: 23, title: "Aire d'un rectangle", difficulty: "facile", theme: "premiers-pas",
    statement: "Retourne l'aire d'un rectangle de `largeur` sur `hauteur`.",
    starterCode: "def aire_rectangle(largeur, hauteur):\n    pass\n",
    entry: "aire_rectangle",
    tests: [{ args: [3, 4], expected: 12 }, { args: [5, 5], expected: 25 }],
    hiddenTests: [{ args: [0, 7], expected: 0 }, { args: [10, 2], expected: 20 }],
  },
  {
    id: 24, title: "Minutes et secondes", difficulty: "facile", theme: "premiers-pas",
    statement: "Convertit `s` secondes en `[minutes, secondes]`. Ex : `125` → `[2, 5]`.",
    starterCode: "def minutes_secondes(s):\n    pass\n",
    entry: "minutes_secondes",
    tests: [{ args: [125], expected: [2, 5] }, { args: [60], expected: [1, 0] }, { args: [59], expected: [0, 59] }],
    hiddenTests: [{ args: [0], expected: [0, 0] }, { args: [3661], expected: [61, 1] }],
  },
  {
    id: 25, title: "Le signe", difficulty: "facile", theme: "conditions",
    statement: "Retourne `-1` si `n` est négatif, `1` s'il est positif, `0` s'il est nul.",
    starterCode: "def signe(n):\n    pass\n",
    entry: "signe",
    tests: [{ args: [-5], expected: -1 }, { args: [0], expected: 0 }, { args: [7], expected: 1 }],
    hiddenTests: [{ args: [-100], expected: -1 }, { args: [42], expected: 1 }],
  },
  {
    id: 26, title: "Majeur ?", difficulty: "facile", theme: "conditions",
    statement: "Retourne `True` si `age` est supérieur ou égal à 18.",
    starterCode: "def est_majeur(age):\n    pass\n",
    entry: "est_majeur",
    tests: [{ args: [18], expected: true }, { args: [17], expected: false }, { args: [25], expected: true }],
    hiddenTests: [{ args: [0], expected: false }, { args: [100], expected: true }],
  },
  {
    id: 27, title: "Est-ce une voyelle ?", difficulty: "facile", theme: "conditions",
    statement: "Retourne `True` si le caractère `c` est une voyelle (`a e i o u y`, en minuscule).",
    starterCode: "def est_voyelle(c):\n    pass\n",
    entry: "est_voyelle",
    tests: [{ args: ["a"], expected: true }, { args: ["b"], expected: false }, { args: ["y"], expected: true }],
    hiddenTests: [{ args: ["e"], expected: true }, { args: ["z"], expected: false }],
  },
  {
    id: 28, title: "Maximum de trois", difficulty: "moyen", theme: "conditions",
    statement: "Retourne le plus grand des trois nombres `a`, `b`, `c` **sans utiliser `max()`**.",
    starterCode: "def max_de_trois(a, b, c):\n    pass\n",
    entry: "max_de_trois",
    tests: [{ args: [1, 2, 3], expected: 3 }, { args: [5, 1, 2], expected: 5 }, { args: [2, 9, 4], expected: 9 }],
    hiddenTests: [{ args: [7, 7, 3], expected: 7 }, { args: [-1, -5, -2], expected: -1 }],
  },
  {
    id: 29, title: "Année bissextile", difficulty: "moyen", theme: "conditions",
    statement: "Retourne `True` si `annee` est bissextile : divisible par 4, sauf les multiples de 100 qui ne sont pas multiples de 400.",
    starterCode: "def bissextile(annee):\n    pass\n",
    entry: "bissextile",
    tests: [{ args: [2024], expected: true }, { args: [2023], expected: false }, { args: [2000], expected: true }, { args: [1900], expected: false }],
    hiddenTests: [{ args: [2400], expected: true }, { args: [2100], expected: false }],
  },
  {
    id: 30, title: "La mention", difficulty: "moyen", theme: "conditions",
    statement: "Selon `note` (sur 20), retourne : `\"insuffisant\"` (< 10), `\"passable\"` (< 12), `\"assez bien\"` (< 14), `\"bien\"` (< 16), sinon `\"très bien\"`.",
    starterCode: "def mention(note):\n    pass\n",
    entry: "mention",
    tests: [{ args: [8], expected: "insuffisant" }, { args: [11], expected: "passable" }, { args: [13], expected: "assez bien" }, { args: [15], expected: "bien" }, { args: [18], expected: "très bien" }],
    hiddenTests: [{ args: [10], expected: "passable" }, { args: [16], expected: "très bien" }, { args: [9], expected: "insuffisant" }],
  },
  {
    id: 31, title: "Somme jusqu'à n", difficulty: "facile", theme: "boucles",
    statement: "Retourne la somme de tous les entiers de 1 à `n` inclus. Ex : `5` → `15`.",
    starterCode: "def somme_jusqua(n):\n    pass\n",
    entry: "somme_jusqua",
    tests: [{ args: [5], expected: 15 }, { args: [1], expected: 1 }, { args: [0], expected: 0 }],
    hiddenTests: [{ args: [100], expected: 5050 }, { args: [10], expected: 55 }],
  },
  {
    id: 32, title: "Table de multiplication", difficulty: "moyen", theme: "boucles",
    statement: "Retourne la liste des 10 premiers multiples de `n` (de `n×1` à `n×10`).",
    starterCode: "def table_multiplication(n):\n    pass\n",
    entry: "table_multiplication",
    tests: [{ args: [2], expected: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20] }],
    hiddenTests: [{ args: [5], expected: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50] }, { args: [1], expected: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] }],
  },
  {
    id: 33, title: "Compter les chiffres", difficulty: "moyen", theme: "boucles",
    statement: "Retourne le nombre de chiffres de l'entier `n` (`n ≥ 0`). Ex : `12345` → `5`. `0` compte pour 1 chiffre.",
    starterCode: "def compter_chiffres(n):\n    pass\n",
    entry: "compter_chiffres",
    tests: [{ args: [0], expected: 1 }, { args: [7], expected: 1 }, { args: [12345], expected: 5 }, { args: [100], expected: 3 }],
    hiddenTests: [{ args: [999999], expected: 6 }, { args: [1000000], expected: 7 }],
  },
  {
    id: 34, title: "Puissance", difficulty: "moyen", theme: "boucles",
    statement: "Retourne `base` à la puissance `exposant` **sans utiliser `**` ni `pow()`**. On a `base⁰ = 1`.",
    starterCode: "def puissance(base, exposant):\n    pass\n",
    entry: "puissance",
    tests: [{ args: [2, 3], expected: 8 }, { args: [5, 0], expected: 1 }, { args: [3, 2], expected: 9 }],
    hiddenTests: [{ args: [2, 10], expected: 1024 }, { args: [7, 1], expected: 7 }],
  },
  {
    id: 35, title: "Initiale en majuscule", difficulty: "facile", theme: "chaines",
    statement: "Retourne `mot` avec sa **première lettre** en majuscule. Ex : `\"chat\"` → `\"Chat\"`. La chaîne peut être vide.",
    starterCode: "def majuscule_initiale(mot):\n    pass\n",
    entry: "majuscule_initiale",
    tests: [{ args: ["chat"], expected: "Chat" }, { args: [""], expected: "" }, { args: ["a"], expected: "A" }],
    hiddenTests: [{ args: ["bonjour"], expected: "Bonjour" }],
  },
  {
    id: 36, title: "Supprimer les espaces", difficulty: "facile", theme: "chaines",
    statement: "Retourne `s` sans aucun espace.",
    starterCode: "def supprimer_espaces(s):\n    pass\n",
    entry: "supprimer_espaces",
    tests: [{ args: ["a b c"], expected: "abc" }, { args: ["  x  "], expected: "x" }, { args: [""], expected: "" }],
    hiddenTests: [{ args: ["bonjour le monde"], expected: "bonjourlemonde" }],
  },
  {
    id: 37, title: "Compter un caractère", difficulty: "moyen", theme: "chaines",
    statement: "Retourne le nombre de fois où le caractère `c` apparaît dans `s`.",
    starterCode: "def compter_caractere(s, c):\n    pass\n",
    entry: "compter_caractere",
    tests: [{ args: ["banane", "a"], expected: 2 }, { args: ["xyz", "a"], expected: 0 }],
    hiddenTests: [{ args: ["", "a"], expected: 0 }, { args: ["aaa", "a"], expected: 3 }],
  },
  {
    id: 38, title: "Compter les mots", difficulty: "moyen", theme: "chaines",
    statement: "Retourne le nombre de mots de `phrase` (les mots sont séparés par des espaces ; attention aux espaces multiples).",
    starterCode: "def compter_mots(phrase):\n    pass\n",
    entry: "compter_mots",
    tests: [{ args: ["bonjour le monde"], expected: 3 }, { args: ["salut"], expected: 1 }, { args: [""], expected: 0 }],
    hiddenTests: [{ args: ["  un   deux  "], expected: 2 }],
  },
  {
    id: 39, title: "Moyenne d'une liste", difficulty: "moyen", theme: "algos",
    statement: "Retourne la moyenne des nombres de `nombres` (la liste n'est jamais vide).",
    starterCode: "def moyenne_liste(nombres):\n    pass\n",
    entry: "moyenne_liste",
    tests: [{ args: [[2, 4, 6]], expected: 4.0 }, { args: [[5]], expected: 5.0 }, { args: [[1, 2, 3, 4]], expected: 2.5 }],
    hiddenTests: [{ args: [[10, 20]], expected: 15.0 }],
  },
  {
    id: 40, title: "Des doublons ?", difficulty: "moyen", theme: "algos",
    statement: "Retourne `True` si `nombres` contient au moins un doublon, sinon `False`.",
    starterCode: "def a_doublons(nombres):\n    pass\n",
    entry: "a_doublons",
    tests: [{ args: [[1, 2, 3]], expected: false }, { args: [[1, 2, 2]], expected: true }, { args: [[]], expected: false }],
    hiddenTests: [{ args: [[5, 5]], expected: true }, { args: [[1, 2, 3, 4, 5]], expected: false }],
  },
];

export const TOTAL_LEVELS = LEVELS.length;
